language: node_js
 
node_js:
  - 'lts/*'

sudo: required
dist: trusty

addons:
  chrome: stable

cache:
  npm: true
  directories:
    - ~/ .npm
    - ./node_modules
    - ~/ .cache

before_install:
  # Fixes an issue where the max file watch count is exceeded, triggering ENOSPC
  # https://stackoverflow.com/questions/22475849/node-js-error-enospc#32600959
  - echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

install:
  - npm install

# before_script:
#   - npm run build

jobs:
  fail_fast: true

  include:
    - stage: Testing
      name: Unit tests
      script: npm run test:ci
    - name: Cypress cucumber tests
      script: npm run test:cypress:ci
 
after_script:
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls

# deploy:
#  provider: pages
#  skip_cleanup: true
#  github_token: $GITHUB_TOKEN
#  local_dir: build
#  on:
#    branch: master

